"""add orders

Revision ID: 8b1c06fb2131
Revises: 111c01eef9d1
Create Date: 2026-08-10 08:14:34.840643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b1c06fb2131'
down_revision: Union[str, None] = '111c01eef9d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # CREATE SCHEMA isn't autogenerated — added by hand.
    op.execute('CREATE SCHEMA IF NOT EXISTS orders')
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='orders'
    )
    op.create_index(op.f('ix_orders_orders_id'), 'orders', ['id'], unique=False, schema='orders')
    op.create_index(op.f('ix_orders_orders_product_id'), 'orders', ['product_id'], unique=False, schema='orders')
    op.create_index(op.f('ix_orders_orders_user_id'), 'orders', ['user_id'], unique=False, schema='orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_orders_user_id'), table_name='orders', schema='orders')
    op.drop_index(op.f('ix_orders_orders_product_id'), table_name='orders', schema='orders')
    op.drop_index(op.f('ix_orders_orders_id'), table_name='orders', schema='orders')
    op.drop_table('orders', schema='orders')
    # ### end Alembic commands ###
    op.execute('DROP SCHEMA IF EXISTS orders')
