"""initial schema

Revision ID: 111c01eef9d1
Revises: 
Create Date: 2026-08-10 00:43:55.833304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '111c01eef9d1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # CREATE SCHEMA isn't autogenerated — added by hand.
    op.execute('CREATE SCHEMA IF NOT EXISTS users')
    op.execute('CREATE SCHEMA IF NOT EXISTS products')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.create_index(op.f('ix_users_users_email'), 'users', ['email'], unique=True, schema='users')
    op.create_index(op.f('ix_users_users_id'), 'users', ['id'], unique=False, schema='users')
    op.create_index(op.f('ix_users_users_username'), 'users', ['username'], unique=True, schema='users')
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='products'
    )
    op.create_index(op.f('ix_products_products_created_by_user_id'), 'products', ['created_by_user_id'], unique=False, schema='products')
    op.create_index(op.f('ix_products_products_id'), 'products', ['id'], unique=False, schema='products')
    op.create_index(op.f('ix_products_products_name'), 'products', ['name'], unique=False, schema='products')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_products_name'), table_name='products', schema='products')
    op.drop_index(op.f('ix_products_products_id'), table_name='products', schema='products')
    op.drop_index(op.f('ix_products_products_created_by_user_id'), table_name='products', schema='products')
    op.drop_table('products', schema='products')
    op.drop_index(op.f('ix_users_users_username'), table_name='users', schema='users')
    op.drop_index(op.f('ix_users_users_id'), table_name='users', schema='users')
    op.drop_index(op.f('ix_users_users_email'), table_name='users', schema='users')
    op.drop_table('users', schema='users')
    # ### end Alembic commands ###
    op.execute('DROP SCHEMA IF EXISTS products')
    op.execute('DROP SCHEMA IF EXISTS users')
